Listabierta\Bundle\MunicipalesBundle\Entity\AdminCandidacy:
    type: entity
    table: admin_candidacy
    repositoryClass: Listabierta\Bundle\MunicipalesBundle\Entity\AdminCandidacyRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
        dni:
            type: string
            length: '15'
        email:
            type: string
            length: 255
            unique: TRUE
        
        username:
            type: string
            length: 25
            unique: TRUE
            
        password:
            type: string
            length: 255
           
        isActive:
            type: boolean
                
        province:
            type: string
            length: 255
        town:
            type: string
            length: 255
        phone:
            type: string
            length: '20'
        address:
            type: string
            length: '255'   
            nullable: TRUE
        ethereum_results_address:
            type: string
            length: '255'
            nullable: TRUE
        ethereum_network_name:
            type: string
            length: '255'
            nullable: TRUE
        todate:
            type: datetime
            nullable: TRUE
        fromdate:
            type: datetime
            nullable: TRUE
        total_days:
            type: integer
            nullable: TRUE
        borda_points:
            type: array
            nullable: TRUE
            default: "{ 0 : 0, 1: 1, 2: 1/2, 3: 1/3,4: 1/4,5: 1/5,6: 1/6,7: 1/7,8: 1/8,9: 1/9,10: 1/10}"
            
    lifecycleCallbacks: {  }
