Listabierta\Bundle\MunicipalesBundle\Entity\Voter:
    type: entity
    table: voter
    repositoryClass: Listabierta\Bundle\MunicipalesBundle\Entity\VoterRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
        dni:
            type: string
            length: '15'
        email:
            type: string
            length: 255
        admin_id:
            type: integer
            nullable: TRUE
        # Not needed for now
        #username:
        #    type: string
        #    length: '25'
        #password:
        #    type: string
        #    length: 255
        isActive:
            type: boolean
        phone:
            type: string
            length: '20'
            
        academic_level:
            type: integer
            nullable: TRUE
            
        languages:
            type: array
            nullable: TRUE
            
        job_experience:
            type: array
            nullable: TRUE
            
        town_activities:
            type: array
            nullable: TRUE
            
        govern_priorities:
            type: array
            nullable: TRUE        
        
        public_values:
            type: array
            nullable: TRUE   
            
        vote_ip:
            type: integer
            nullable: TRUE   
        
        vote_info:
            type: array
            nullable: TRUE   
        
        vote_response_string:
            type: string
            nullable: TRUE
            
        vote_response_time:
            type: integer
            nullable: TRUE
            
    lifecycleCallbacks: {  }
