<?php 
return array (
  'home.html_title' => 'Municipales 2015 - Home',
  'home.h1_title' => 'Municipales 2015',
  'home.steps_h2' => 'Pasos',
  'home.step_h2' => 'Paso',
  'home.steps' => 'Para dar de alta una candidatura ciudadana debes',
  'home.featured' => 'Abre tu ayuntamiento a la ciudadanía en estas elecciones municipales de mayo 2015',
  'home.open_council' => 'Abre tu ayuntamiento a la ciudadan&iacute;a en estas elecciones municipales de mayo 2015',
  'home.who_we_are' => '¿Quienes somos?',
  'home.who_h3' => 'Empieza por aquí',
  'home.intro_p1' => 'es el fruto de un esfuerzo de financiación colectiva y de un equipo de trabajo que pretende abrir las organizaciones a la ciudadanía. Entre estas organizaciones ocupan un lugar destacado los Ayuntamientos. Puedes utilizar esta herramienta para hacer una candidatura de listas abiertas en tu municipio, es gratuita pero tiene limitaciones. Si quieres utilizar una solución más avanzada te sugerimos que utilices NVotes.com que tiene costes asociados. Puedes contactar con la cooperativa http://enreda.coop/ para implementar tanto listAbierta.org como Nvotes u otras soluciones de Participación Ciudadana."',
  'home.intro_p2' => 'La elección de candidatos y candidatas en listas abiertas para los comicios municipales permite que los electos se “deban” a los ciudadanos que los han elegido, y no a quien les hubiese incluido en una lista cerrada o negociada.',
  'home.intro_p3' => 'Si estás <b>directamente implicado en la organización</b> de una candidatura de listas abiertas en tu municipio para las próximas elecciones de mayo de 2.015, puedes organizarla con esta herramienta online sin coste y con resultados auditables, porque otra forma de gobernar tu Ayuntamiento es posible y necesaria.',
  'home.intro_p4' => 'Es muy importante que antes de empezar el proceso de registro de la candidatura, veas este tutorial del proceso completo.',
  'home.intro_p5' => '¿Cómo funciona la herramienta de listas abiertas municipales?',
  'home.step_1' => 'Regístrate y registra el municipio de la candidatura',
  'home.step_2' => 'Establece las condiciones de la candidatura ciudadana',
  'home.step_3' => 'Establece los plazos de votación',
  'home.step_4' => 'Reserva una dirección de internet',
  'home.step_5' => 'Alta de candidatos y candidatas',
  'home.step_6' => 'Validación de candidatos y candidatas',
  'home.step_7' => 'Votaciones',
  'home.step_8' => 'Verificación del voto y resultados',
  'home.step_9' => 'Presentación de las listas electas',
  'home.start_here' => 'Iniciar el registro',
  'home.welcome' => '&iexcl;Bienvenidos al sitio!',
  'header.languages.es_eu' => 'Euskera',
  'header.languages.es_ca' => 'Català',
  'header.languages.es_gl' => 'Galego',
  'header.languages.es_es' => 'Español',
  'candidacy.html_title' => 'Municipales 2015 - Alta de candidatura ciudadana',
  'candidacy.h1_title' => 'Regístrate y registra el municipio de la candidatura',
  'candidacy.verify_msg' => 'Confirma el registro y las condiciones enviando desde tu móvil un SMS con la palabra ACEPTO al número %sms_inbound_number%, después haz clic en CONTINUAR',
  'candidacy.verify_extra' => 'El coste del mensaje es de unos 10 céntimos de euro (o gratis, depende del coste de tu operadora) no es un sms premium y listabierta.org no cobra por este servicio.',
  'candidacy.step_conditions.html_title' => 'Municipales 2015 - Condiciones de alta de candidatura ciudadana',
  'candidacy.step_conditions.h1_title' => 'Regístrate y registra el municipio de la candidatura',
  'candidacy.step_conditions.p1_title' => 'Al iniciar el registro aceptas las siguientes condiciones',
  'candidacy.step_conditions.p1_content' => 'Que formas parte un colectivo (partido político, coalición de partidos o agrupación de electores) que desea presentarse a los comicios municipales que se celebrarán el 24 de mayo de 2.015 y que para ello tienen la intención de registrarse en plazo y forma en la correspondiente junta electoral provincial.',
  'candidacy.step_conditions.p2_content' => 'Que has sido designado por dicho colectivo para efectuar el alta del municipio en la presente herramienta de voto de listas abiertas, no existiendo conflicto interno en cuanto a su uso.',
  'candidacy.step_conditions.p3_content' => 'Que dicho colectivo comprende y acepta las limitaciones del uso de la herramienta en cuanto al sistema de voto y su verificación.',
  'candidacy.step_conditions.p4_content' => 'Que dicho colectivo comprende y acepta que el proceso de verificación y aceptación de las candidaturas lo efectúa el administrador o administradora de la votación.',
  'candidacy.step_conditions.p5_content' => 'Que mediante el acto de registro estás dando tu consentimiento expreso al tratamiento de los datos personales que aportas, según lo dispuesto en el artículo 6 de la LOPD y que podrás ejercer tus derechos en los términos dispuestos por el artículo 5 de la LOPD.',
  'candidacy.step_conditions.p6_content' => 'Que la información que aportas durante el registro es cierta, tanto los datos personales como las condiciones de la votación, de la candidatura y su programa. <b>Ten en cuenta que no podrás modificarla más adelante, ya que los datos de registro se utilizan para identificarte como usuario único</b>.',
  'candidacy.step_conditions.accept' => 'ACEPTAS ESTAS CONDICIONES',
  'candidacy.step_conditions.continue' => '<i class="ace-icon fa fa-check bigger-110"></i> Continuar',
  'candidacy.step1.name' => 'Nombre',
  'candidacy.step1.lastname' => 'Apellidos',
  'candidacy.step1.dni' => 'DNI',
  'candidacy.step1.username' => 'Usuario',
  'candidacy.step1.password' => 'Contraseña',
  'candidacy.step1.email' => 'Email',
  'candidacy.step1.province' => 'Provincia del municipio',
  'candidacy.step1.town' => 'Nombre del municipio',
  'candidacy.step1.phone' => 'Número de móvil',
  'candidacy.step1.previous' => 'Anterior',
  'candidacy.step1.continue' => 'Continuar <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'candidacy.step1.explanation_dni' => '¿Por que necesitamos tu DNI y tu número de móvil? Para evitar el spam y el registro múltiple de candidaturas. Para poder continuar con el registro necesitamos que proporciones ambos datos de forma correcta.',
  'candidacy.step1.explanation' => 'Explicación',
  'candidacy.step1.dni_info' => 'Sin introducir guión entre número y letra',
  'candidacy.step1.username_info' => 'Anota tu nombre de usuario',
  'candidacy.step1.password_info' => 'Anota tu contraseña',
  'candidacy.step1.email_info' => 'Recibirás un email de confirmación',
  'candidacy.step1.phone_info' => 'Deberás confirmarlo con un mensaje en el siguiente paso, si introduces un número incorrecto, no podrás continuar',
  'candidacy.step1.warning_text' => '<b>Atención</b>: es imprescindible que introduzcas los datos de registro de forma correcta, incluyendo tu número de móvil, un error en los datos de registro implica que otra persona tendrá que dar de alta esta candidatura ciudadana. Si tienes dudas del proceso, vuelve a ver el video <a href="https://www.youtube.com/watch?v=v-ysTeRE9lc" title="listAbierta.org - Abre las organizaciones a la ciudadanía (Versión Corta)">aquí</a>. El sistema no admite candidaturas “de prueba”.',
  'candidacy.step_verify.html_title' => 'Municipales 2015 - Alta de candidatura ciudadana',
  'candidacy.step_verify.h1_title' => 'Verifica tu número de móvil',
  'candidacy.step_verify.continue' => 'Continuar <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'candidacy.step_verify.previous' => 'Anterior',
  'candidacy.step2.html_title' => 'Municipales 2015 - Alta de candidatura ciudadana',
  'candidacy.step2.h1_title' => 'Establece las condiciones de la candidatura ciudadana',
  'candidacy.step2.p1' => 'Sube en formato PDF aquellas condiciones que deban aceptar los candidatos o candidatas (una, algunas, todas o ninguna) para presentarse en la candidatura ciudadana. Por ejemplo: El programa de la candidatura, las condiciones legales y la veracidad de la información aportada, el mandato revocatorio y participativo, el código ético, la aceptación del censo y el sistema de voto, etc.  Si no subes ninguna condición, te recomendamos que busques algún método alternativo para verificar que el candidato o candidata va a cumplirlas antes de su inclusión en las listas.',
  'candidacy.step2.program' => 'El programa de la candidatura',
  'candidacy.step2.legal_conditions' => 'Condiciones legales y veracidad de la información aportada de candidatos y candidatas',
  'candidacy.step2.recall_term' => 'El mandato revocatorio del candidato',
  'candidacy.step2.participatory_term' => 'El código ético de la candidatura',
  'candidacy.step2.voter_conditions' => 'Las condiciones para poder participar como votante (censo y aceptación del sistema de votación)',
  'candidacy.step2.technical_constrains' => 'Las limitaciones técnicas y legales del sistema de voto.',
  'candidacy.step2.continue' => 'Continuar <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'candidacy.step2.previous' => 'Anterior',
  'candidacy.step2.example' => 'Ejemplo',
  'candidacy.step3.html_title' => 'Municipales 2015 - Alta de candidatura ciudadana',
  'candidacy.step3.h1_title' => 'Establece los plazos de presentación de candidaturas',
  'candidacy.step3.continue' => 'Continuar <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'candidacy.step3.explanation_date' => 'Plazo de presentación de candidaturas <br/>(mínimo 2 días)',
  'candidacy.step3.from_label' => 'DE',
  'candidacy.step3.to_label' => 'HASTA',
  'candidacy.step3.previous' => 'Anterior',
  'candidacy.step4.html_title' => 'Municipales 2015 - Alta de candidatura ciudadana',
  'candidacy.step4.h1_title' => 'Reserva una dirección de internet',
  'candidacy.step4.continue' => 'Continuar <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'candidacy.step4.previous' => 'Anterior',
  'candidacy.step4.choose_address' => 'Elige tu dirección de internet',
  'candidacy.step4.warning' => 'Si en el espacio en blanco escribes por ejemplo: FuenteovejunaParticipa, las direcciones asociadas a tu candidatura serán del tipo: http://%host%/FuenteovejunaParticipa/...',
  'candidacy.step5.html_title' => 'Municipales 2015 - Alta de candidatura ciudadana',
  'candidacy.step5.h1_title' => 'Alta de candidatos y candidatas',
  'candidacy.step5.continue' => 'Continuar <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'candidacy.step5.previous' => 'Anterior',
  'candidacy.step5.explanation_link' => 'Proporciona este enlace público a los candidatos y candidatas para que se den de alta rellenando el formulario que les aparecerá',
  'candidacy.step5.register_link' => 'Enlace de Alta',
  'candidacy.step5.send_link' => 'Te hemos enviado una copia de este enlace a tu email',
  'candidacy.step5.next_step_explanation' => 'En el siguiente paso podrás validar a los candidatos y candidatas que se den de alta utilizando el enlace anterior.',
  'candidacy.step6.html_title' => 'Municipales 2015 - Alta de candidatura ciudadana',
  'candidacy.step6.h1_title' => 'Validación de candidatos y candidatas',
  'candidacy.step6.continue' => 'Continuar <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'candidacy.step6.no_candidates' => 'En estos momentos no existe ningun candidato inscrito para validar',
  'candidacy.step6.name_header' => 'Nombre y Apellidos',
  'candidacy.step6.motivational_text_header' => 'Texto motivacional',
  'candidacy.step6.town_activities_explanation_header' => 'Explicación actividades municipales',
  'candidacy.step6.additional_info_header' => 'Biografía',
  'candidacy.step6.photo_header' => 'Foto',
  'candidacy.step6.action_header' => 'Acción',
  'candidacy.step6.accept' => 'Aceptar',
  'candidacy.step6.reject' => 'Rechazar',
  'candidacy.step6.delete' => 'Borrar',
  'candidacy.step6.accepted' => 'Aceptado',
  'candidacy.step6.rejected' => 'Rechazado',
  'candidacy.step6.accept_candidate' => 'Aceptar candidato',
  'candidacy.step6.reject_candidate' => 'Rechazar candidato',
  'candidacy.step6.delete_candidate' => 'Borrar candidato',
  'candidacy.step7.html_title' => 'Municipales 2015 - Alta de candidatura ciudadana',
  'candidacy.step7.h1_title' => 'Inicio y fin de las Votaciones',
  'candidacy.step7.days' => 'Días',
  'candidacy.step7.explanation' => 'Introduce el número de días naturales que permanecerá activa la votación de candidatos desde el inicio de la votación (mínimo dos días).',
  'candidacy.step7.init_vote_explanation' => 'Haz clic en el siguiente botón para iniciar la votación',
  'candidacy.step7.warning_explanation' => 'ATENCIÓN !! Una vez iniciada la votación ya NO SE PODRÁN AÑADIR más candidatos o candidatas. Se proporcionará un enlace que habilitará el registro a los votantes y emitir el voto.',
  'candidacy.step7.start_candidacy' => 'Iniciar votación',
  'candidacy.step7.public_link' => 'Este es el enlace a la votación que puedes hacer público',
  'candidacy.step7.no_finished_candidacy' => 'Aún no puede iniciarse la votación ya que la fecha de finalización de las candidaturas no ha terminado.',
  'candidacy.step7.sent_mail' => 'Te hemos enviado una copia de este enlace a tu email',
  'candidacy.step8.html_title' => 'Municipales 2015 - Alta de candidatura ciudadana',
  'candidacy.step8.h1_title' => 'Verificación del voto y resultados',
  'candidacy.step8.continue' => 'Continuar <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'candidacy.step8.previous' => 'Anterior',
  'candidacy.step8.vote_finished' => 'Votación finalizada',
  'candidacy.step8.audit' => 'Puedes auditar el resultado aquí',
  'candidacy.step8.how_works_tsa' => '¿Cómo funciona el sellado de tiempo?',
  'candidacy.step8.photo' => 'Foto',
  'candidacy.step8.name_lastname' => 'Nombre y Apellidos',
  'candidacy.step8.dni' => 'DNI',
  'candidacy.step8.phone' => 'Número de Móvil',
  'candidacy.step8.total_points' => 'Total de puntos',
  'candidacy.step8.position' => 'Posición',
  'candidacy.step8.vote_not_finished_warning' => 'La votación aún no ha finalizado y aún no estan disponibles los resultados finales',
  'candidacy.step8.vote_start_date' => 'Fecha de inicio de votaciones',
  'candidacy.step8.vote_end_date' => 'Fecha de cierre de votaciones',
  'candidacy.step8.header_p1' => 'Una vez finalizada la votación, aparecerán en esta pantalla los resultados de la suma de puntos en un listado, ordenados de mayor a menor puntuación',
  'candidacy.step8.header_p1_h3' => '¿Cómo funciona el sistema de puntuación?',
  'candidacy.step8.header_p2' => 'El sistema que listabierta.org ha escogido es el Borda Modificado, porque es sencillo de entender por el votante y permite una elección más diversa y consensuada. En este caso el votante asigna a los candidatos o candidatas preseleccionados una posición que va del primer al quinto lugar. Una vez establecido el orden, procede a votar. Internamente, el recuento de puntos funciona de la siguiente forma',
  'candidacy.step8.header_li1' => 'El candidato o candidata elegido en primer lugar recibe un punto (1)',
  'candidacy.step8.header_li2' => 'El candidato o candidata elegido en segundo lugar recibe medio punto (½) = 0,5 puntos',
  'candidacy.step8.header_li3' => 'El candidato o candidata elegido en tercer lugar recibe un tercio de punto (⅓) = 0, 33 puntos',
  'candidacy.step8.header_li4' => 'El candidato o candidata elegido en cuarto lugar recibe un cuarto de punto (¼) = 0, 25 puntos',
  'candidacy.step8.header_li5' => 'El candidato o candidata elegido en quinto  lugar recibe una quinta parte de punto (⅕) = 0,20 puntos',
  'candidacy.step9.html_title' => 'Municipales 2015 - Alta de candidatura ciudadana',
  'candidacy.step9.h1_title' => 'Presentación de las listas electas',
  'candidacy.step9.continue' => 'Iniciar votación',
  'candidacy.step9.result' => 'Resultados de la votación',
  'candidacy.step9.link_result' => 'Enlace a los resultados de la elección',
  'candidacy.step9.public_link' => 'Proporciona este enlace público para mostrar los resultados de la votación',
  'candidacy.recover_password.h1_title' => 'Recuperar contraseña',
  'candidacy.recover_password.header' => 'Cuenta administrador',
  'candidacy.recover_password.h1_subtitle' => 'Recupera la contraseña de tu cuenta administrador',
  'candidacy.recover_password.oldPassword' => 'Contraseña antigua',
  'candidacy.recover_password.newPassword' => 'Contraseña nueva',
  'town.html_title' => 'Municipales 2015 - Vota en la candidatura ciudadana',
  'town.h1_title' => 'Registrate como votante',
  'town.verify_msg' => 'Confirma el registro y las condiciones enviando desde tu móvil un SMS con la palabra ACEPTO al número %sms_inbound_number%, después haz clic en CONTINUAR',
  'town.verify_extra' => 'El coste del mensaje es de unos 10 céntimos de euro (o gratis, depende del coste de tu operadora) no es un sms premium y listabierta.org no cobra por este servicio.',
  'town.step1.welcome' => 'Bienvenido o bienvenida a la votación de la candidatura ciudadana de',
  'town.step1.welcome_more' => 'Como primer paso has de registrarte como votante. <br />Si introduces datos erróneos, no podrás modificarlos más adelante',
  'town.step1.header' => 'Registrate como votante',
  'town.step1.name' => 'Nombre',
  'town.step1.lastname' => 'Apellidos',
  'town.step1.dni' => 'DNI',
  'town.step1.email' => 'Email',
  'town.step1.username' => 'Usuario',
  'town.step1.password' => 'Contraseña',
  'town.step1.phone' => 'Número de móvil',
  'town.step1.continue' => 'Continuar <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'town.step1.explanation_dni' => '¿Por que necesitamos tu DNI y tu número de móvil? Para evitar el spam y el registro múltiple de candidaturas. Para poder continuar con el registro necesitamos que proporciones ambos datos de forma correcta.',
  'town.step1.explanation' => 'Explicación',
  'town.step1.warning_text' => '<b>Atención</b>: es imprescindible que introduzcas los datos de registro de forma correcta, incluyendo tu número de móvil, un error en los datos de registro implica que no podrás votar',
  'town.step_verify.html_title' => 'Municipales 2015 - Registrate como votante',
  'town.step_verify.h1_title' => 'Verifica tu número de móvil',
  'town.step_verify.continue' => 'Continuar <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'town.step_verify.previous' => 'Anterior',
  'town.step_verify.verify_conditions_header' => 'Requisitos para el voto:',
  'town.step_verify.verify_conditions_op1' => 'Apoyas esta candidatura ciudadana de listas abiertas y estás conforme con este proceso de registro.',
  'town.step_verify.verify_conditions_op2' => 'Estás dando tu consentimiento expreso al tratamiento tus los datos personales según lo dispuesto en el artículo 5 y 6 de la LOPD y podremos contactarte en tu email con información estrictamente relacionada con el proceso de votación, nunca cederemos tus datos de registro a terceros.',
  'town.step_verify.verify_conditions_op3' => 'La información que aportas durante este registro es cierta y  tu residencia habitual se encuentra en el municipio objeto de la votación',
  'town.step2.header' => 'Filtra candidatos',
  'town.step2.html_title' => 'Municipales 2015 - Vota en la candidatura ciudadana - Paso 2',
  'town.step2.filter_title' => '¿Qué criterios deseas utilizar para seleccionar a los candidatos y candidatas?',
  'town.step2.filter_p1' => 'Ten en cuenta que si no aplicas ningún filtro, te aparecerá la totalidad de candidatos y candidatas que se han presentado y puede resultar tedioso ver todos los perfiles y después puntuarlos, así que si tienes alguna preferencia clara márcala, posteriormente podrás revisar tus filtros.',
  'town.step2.h1_title' => 'Filtra candidatos por nivel academico',
  'town.step2.academic_level' => '¿Quieres elegir el nivel académico que prefieres que tenga el candidato o candidata?',
  'town.step2.languages' => '¿Es bueno que hable alguno de estos idiomas?',
  'town.step2.continue' => 'Continuar <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'town.step2.previous' => 'Anterior',
  'town.step3.header' => 'Seleciona experiencia laboral',
  'town.step3.html_title' => 'Municipales 2015 - Vota en la candidatura ciudadana - Paso 3',
  'town.step3.h1_title' => 'Seleciona experiencia laboral',
  'town.step3.continue' => 'Continuar <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'town.step3.previous' => 'Anterior',
  'town.step3.job_experience_title' => '¿Qué campo de experiencia laboral te gustaría que hubiese desarrollado?',
  'town.step4.header' => 'Selecciona actividades municipales',
  'town.step4.html_title' => 'Municipales 2015 - Vota en la candidatura ciudadana - Paso 4',
  'town.step4.h1_title' => 'Selecciona actividades municipales',
  'town.step4.continue' => 'Continuar <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'town.step4.previous' => 'Anterior',
  'town.step4.town_activities_title' => '¿Qué experiencia relacionada con el desempeño municipal te gustaría que hubiese desarrollado?',
  'town.step5.header' => 'Selecciona prioridades municipales',
  'town.step5.html_title' => 'Municipales 2015 - Vota en la candidatura ciudadana - Paso 5',
  'town.step5.h1_title' => 'Selecciona prioridades municipales',
  'town.step5.continue' => 'Continuar <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'town.step5.previous' => 'Anterior',
  'town.step5.govern_priorities_title' => '¿En qué actividades crees que debería centrarse con prioridad el gobierno municipal ?',
  'town.step5.public_values_title' => '¿Qué valores morales consideras de mayor importancia para el desempeño de la función pública?',
  'town.step6.header' => 'Asigna importancia',
  'town.step6.html_title' => 'Municipales 2015 - Vota en la candidatura ciudadana - Paso 6',
  'town.step6.h1_title' => 'Asigna importancia',
  'town.step6.continue' => 'Ver candidatos seleccionados <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'town.step6.previous' => 'Anterior',
  'town.step7_confirmation.header' => 'Elige candidatos',
  'town.step7_confirmation.html_title' => 'Municipales 2015 - Vota en la candidatura ciudadana - Paso 7',
  'town.step7_confirmation.h1_title' => 'Seleccion previa de candidatos',
  'town.step7_confirmation.continue' => 'Ver candidatos seleccionados <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'town.step7_confirmation.previous' => 'Revisar criterios',
  'town.step7_confirmation.filter_selection' => 'Con tu selección actual de filtros se te mostrarán',
  'town.step7_confirmation.advice' => 'Te aconsejamos un máximo de 10',
  'town.step7_confirmation.candidates_of' => 'candidatos/as de',
  'town.step7.header' => 'Elige candidatos',
  'town.step7.html_title' => 'Municipales 2015 - Vota en la candidatura ciudadana - Paso 7',
  'town.step7.h1_title' => 'Elige candidatos',
  'town.step7.continue' => 'VOTA <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'town.step7.previous' => 'Anterior',
  'town.step8.header' => 'Asigna puntuaciones',
  'town.step8.html_title' => 'Municipales 2015 - Vota en la candidatura ciudadana - Paso 8',
  'town.step8.h1_title' => 'Asigna puntuaciones',
  'town.step8.continue' => 'Continuar <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'town.step8.previous' => 'Anterior',
  'town.step8.congratulations' => '<strong><i class="mine-icon fa fa-check"></i> ¡Enhorabuena!</strong> Tu voto ha sido procesado correctamente',
  'town.step9.header' => 'Fin',
  'town.step9.html_title' => 'Municipales 2015 - Alta de candidatura ciudadana',
  'town.step9.h1_title' => 'Fin',
  'town.step9.previous' => 'Anterior',
  'town.step9.headline' => 'Resultados públicos de la votación',
  'town.step9.headin1' => 'Resultados de la elección del municipio',
  'town.step9.headin2' => 'en',
  'town.step9.candidates_voted' => 'Candidatos votados',
  'town.step9.total_voters' => 'Total votantes',
  'town.step9.total_points' => 'Total de puntos',
  'town.step9.position' => 'Posición',
  'candidate.html_title' => 'Municipales 2015 - Alta de candidato',
  'candidate.h1_title' => 'Regístrate como candidato o candidata',
  'candidate.step1.header' => 'Regístrate como candidato o candidata',
  'candidate.step1.p1' => 'Antes de registrarte como candidato o candidata en la candidatura ciudadana <b>%address%</b>, del municipio <b>%town%</b>debes ver este video explicativo del proceso de registro.',
  'candidate.step1.p2' => 'El plazo de presentación de candidaturas establecido es desde %fromdate% hasta %todate%',
  'candidate.step1.name' => 'Nombre',
  'candidate.step1.lastname' => 'Apellidos',
  'candidate.step1.dni' => 'DNI',
  'candidate.step1.email' => 'Email',
  'candidate.step1.phone' => 'Número de móvil',
  'candidate.step1.continue' => 'Continuar <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'candidate.step1.warning_text' => '<b>Atención</b>: es imprescindible que introduzcas los datos de registro de forma correcta, incluyendo tu número de móvil, un error en los datos de registro implica que no podrás dar de alta tu candidatura. Si tienes dudas del proceso, vuelve a ver el video <a href="https://www.youtube.com/watch?v=v-ysTeRE9lc" title="listAbierta.org - Abre las organizaciones a la ciudadanía (Versión Corta)">aquí</a>. El sistema no admite candidaturas “de prueba”.',
  'candidate.verify_msg' => 'Confirma el registro y las condiciones enviando desde tu móvil un SMS con la palabra ACEPTO al número %sms_inbound_number%, después haz clic en CONTINUAR',
  'candidate.verify_extra' => 'El coste del mensaje es de unos 10 céntimos de euro (o gratis, depende del coste de tu operadora) no es un sms premium y listabierta.org no cobra por este servicio.',
  'candidate.step_verify.html_title' => 'Municipales 2015 - Alta de candidato',
  'candidate.step_verify.h1_title' => 'Verifica tu número de móvil',
  'candidate.step_verify.continue' => 'Continuar <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'candidate.step_verify.previous' => 'Anterior',
  'candidate.step2.header' => 'Firma documentos',
  'candidate.step2.p1' => 'Debes firmar tu conformidad con los condicionantes de la candidatura, para ello haz clic en “Descargar” y firma (digital o manualmente) el documento, y una vez firmado lo adjuntas haciendo clic en “Examinar”.  Cuando hayas hecho lo mismo con todos los documentos,  haz clic en continuar. Puede que el administrador de la candidatura no ha subido ninguna condición, entonces, simplemente haz clic en continuar',
  'candidate.step2.program' => 'Aceptación del programa de la candidatura',
  'candidate.step2.legal_conditions' => 'Cumplimiento de las condiciones legales y veracidad de la información aportada',
  'candidate.step2.recall_term' => 'Aceptación del mandato revocatorio del candidato',
  'candidate.step2.participatory_term' => 'Aceptación del mandato participativo del candidato',
  'candidate.step2.voter_conditions' => 'Aceptación del censo disponible y del sistema de votación',
  'candidate.step2.technical_constrains' => 'Aceptación de las limitaciones técnicas y legales del sistema de voto.',
  'candidate.step2.download' => 'Descargar',
  'candidate.step2.previous' => 'Anterior',
  'candidate.step2.continue' => 'Continuar <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'candidate.step3.header' => 'Proporciona tu nivel académico',
  'candidate.step3.academic_level_title' => '¿Cuál es tu nivel académico?',
  'candidate.step3.languages_title' => '¿Eres capáz de mantener una conversación telefónica en alguno de estos idiomas? (puedes seleccionar ninguno o varios)',
  'candidate.step3.previous' => 'Anterior',
  'candidate.step3.continue' => 'Continuar <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'candidate.step4.header' => 'Proporciona tu experiencia laboral',
  'candidate.step4.job_experience_title' => '¿Cuál es el campo de tu experiencia laboral? (Seleccione hasta tres opciones)',
  'candidate.step4.previous' => 'Anterior',
  'candidate.step4.continue' => 'Continuar <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'candidate.step5.header' => 'Proporciona el desempeño municipal',
  'candidate.step5.header_title' => '¿Has tenido alguna experiencia que pueda estar relacionada con las actividades que desarrolla un Ayuntamiento?',
  'candidate.step5.town_activities_title' => '¿Has tenido alguna experiencia relacionada con el desempeño municipal?  (Seleccione hasta tres opciones siempre que tu actividad incluya la coordinación o gestión de un grupo superior a las 10 personas, posteriormente tendrás que explicarlo)',
  'candidate.step5.previous' => 'Anterior',
  'candidate.step5.continue' => 'Continuar <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'candidate.step6.header' => 'Establece prioridades de gobierno',
  'candidate.step6.subheader' => 'Establece las prioridades en las que debería mejorarse la gestión municipal',
  'candidate.step6.govern_priorities_title' => '¿En qué actividades crees que debería centrarse con prioridad el gobierno municipal ? (seleccione hasta tres opciones)',
  'candidate.step6.previous' => 'Anterior',
  'candidate.step6.continue' => 'Continuar <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'candidate.step7.header' => 'Selecciona valores morales',
  'candidate.step7.public_values_title' => '¿Qué valores morales consideras de mayor importancia para el desempeño de la función pública? (elige hasta tres)',
  'candidate.step7.motivation_text_title' => 'Describe tu motivación para presentarte',
  'candidate.step7.town_activities_explanation_title' => 'Describe tu experiencia relacionada',
  'candidate.step7.additional_info_title' => 'Biografía e información adicional que quieras aportar',
  'candidate.step7.url_info_title' => 'Dirección web o URL (vídeo, blog, etc) (opcional)',
  'candidate.step7.profile_image_title' => 'Adjunta foto',
  'candidate.step7.previous' => 'Anterior',
  'candidate.step7.continue' => 'Continuar <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'candidate.final_step.header' => 'Fin',
  'candidate.final_step.end' => '¡Candidatura completada!',
  'login.html_title' => 'Login',
  'login.username' => 'Usuario',
  'login.password' => 'Contraseña',
  'login.access' => 'Acceder',
  'login.remember_me' => 'Recordar mis datos',
  'login.conditions' => 'Accede con tus credenciales de usuario y contraseña',
  'login.recover_password' => '¿Olvidaste tu contraseña?',
  'mail.candidate_created.hello' => 'Hola',
  'mail.candidate_created.account' => 'Este es un mensaje de confirmación de que tu registro de candidato ha sido creado',
  'mail.candidate_created.contact' => 'Puedes comentarle cualquier incidencia al administrador de la candidatura en el correo',
  'mail.admin_created.hello' => 'Hola',
  'mail.admin_created.account' => 'Tu cuenta de administrador de candidatura ha sido creada',
  'mail.admin_created.can_create' => 'Puedes acceder a tu cuenta desde el enlace',
  'mail.admin_created.login' => 'Login',
  'mail.admin_updated.hello' => 'Hola',
  'mail.admin_updated.account' => 'Tu cuenta de administrador de candidatura ha sido actualizada',
  'mail.admin_updated.can_create' => 'Puedes acceder a tu cuenta desde el enlace',
  'mail.admin_updated.login' => 'Login',
  'mail.candidacy_address.hello' => 'Hola',
  'mail.candidacy_address.supply_link' => 'Puedes proporcionar este enlace público a los candidatos y candidatas para que se den de alta rellenando el formulario que les aparecerá',
  'mail.candidacy_vote_address.hello' => 'Hola',
  'mail.candidacy_vote_address.can_public' => 'Puedes proporcionar este enlace público de votacion a los votantes para que procedan rellenando el formulario que les aparecerá',
  'mail.candidate_accepted.hello' => 'Hola',
  'mail.candidate_accepted.accepted' => 'Tu candidatura ha sido aceptada por el administrador',
  'mail.candidate_accepted.admin_email' => 'Dirección de correo del administrador',
  'mail.candidate_rejected.hello' => 'Hola',
  'mail.candidate_rejected.rejected' => 'Tu candidatura ha sido rechazada por el administrador',
  'mail.candidate_rejected.admin_email' => 'Dirección de correo del administrador',
  'mail.candidate_deleted.hello' => 'Hola',
  'mail.candidate_deleted.deleted' => 'Tu candidatura ha sido borrada por el administrador',
  'mail.candidate_deleted.admin_email' => 'Dirección de correo del administrador',
  'mail.candidate_signup.new' => 'Se ha registrado un nuevo candidato con nombre',
  'mail.sms_inbound_verification.your_phone' => 'Tu teléfono',
  'mail.sms_inbound_verification.verify' => 'ha sido verificado correctamente',
  'panel_admin.index.header' => 'Panel Admin',
  'panel_admin.index.hello' => 'Hola',
  'panel_admin.index.logout' => 'Salir',
  'panel_admin.index.manage' => 'En este panel puedes gestionar la candidatura ciudadana',
  'panel_admin.index.not_yet_validated' => 'Aun no has validado tu número de móvil',
  'panel_admin.index.needed_continue' => 'Es necesario validar tu móvil para continuar con cualquier acción',
  'panel_admin.index.your_phone_number' => 'Tu número de móvil',
  'panel_admin.index.is_verified' => 'esta verificado correctamente.',
  'panel_admin.index.modify_personal_data' => 'Modificar datos personales',
  'panel_admin.index.upload_documents' => 'Subir documentos',
  'panel_admin.index.set_candidacy_date' => 'Cambiar/establecer los plazos <br />presentación de candidaturas',
  'panel_admin.index.change_address' => 'Cambiar/establecer <br />dirección de internet',
  'panel_admin.index.candidacy_register' => 'Ver enlace <br />de alta de candidatos/as',
  'panel_admin.index.validate_candidates' => 'Validar candidatos/as',
  'panel_admin.index.set_vote_days' => 'Establecer número de días <br />de la votación (plazo de votación)',
  'panel_admin.index.see_internal_results' => 'Ver resultados internos <br />de la votación',
  'panel_admin.index.see_public_results' => 'Ver enlace de resultados públicos<br /> de la votación',
  'panel_admin.index.verify_msg' => 'Confirma tu cuenta administrador enviando desde tu móvil un SMS con la palabra ACEPTO al número %sms_inbound_number%, después <a href="#" onclick="javascript:window.location.reload()">actualiza/recarga</a> esta página',
  'panel_admin.modify_personal_data.title' => 'Modificar datos personales',
  'panel_admin.modify_personal_data.back' => 'Volver',
  'panel_admin.modify_personal_data.save' => 'Guardar <i class="mine-icon fa fa-arrow-right icon-on-right"></i>',
  'forms.candidacy_step1.password.minMessage' => 'Tu contraseña debe de ser de al menos {{ limit }} caracteres',
  'forms.candidacy_step1.password.maxMessage' => 'Tu contraseña debe de ser mayor de {{ limit }} caracteres',
)
